### ISSUE TITLE
Ассасанс когда коммиты

### ISSUE THREAD

**Issue by ghost** [AraumiTX/Araumi#2]
Ну задолбал уже давай коммить а то хули мы без дела сидим а ты за нас всю работу делаеш так не пойдет

**Comment by C6OI** [comment]
> Ну задолбал уже давай коммить а то хули мы без дела сидим а ты за нас всю работу делаеш так не пойдет

Согласен бро +++

**Comment by ghost** [comment]
О все коммиты вижу issue закрываю

**Comment by C6OI** [comment]
> О все коммиты вижу issue закрываю
> 

Согл бро!!! Асик работает!!!
