### ISSUE TITLE
Не могу собрать

### ISSUE THREAD

**Issue by C6OI** [AraumiTX/Araumi#9]
![image](https://user-images.githubusercontent.com/59257047/135555560-17ffd319-a084-4a59-992e-6126a55e0700.png)
Установил все пакеты, перезапускал вижуал студио, нихуя не ебёт что делать нахуй

**Comment by ghost** [comment]
.NET 6 SDK поставь шизоид

**Comment by C6OI** [comment]
> .NET 6 SDK поставь шизоид

СУКА Я НАПИСАЛ ЧТО Я СТАВИЛ

**Comment by C6OI** [comment]
> > .NET 6 SDK поставь шизоид
> 
> СУКА Я НАПИСАЛ ЧТО Я СТАВИЛ
> 

Ладно я попробую поставить в пятый раз

**Comment by ghost** [comment]
> > .NET 6 SDK поставь шизоид
> 
> СУКА Я НАПИСАЛ ЧТО Я СТАВИЛ

не поставил ты нихуя шизик

**Comment by C6OI** [comment]
Забыл закрыть
